manu_sim: model_system.o calculate_functions.o main.o
	gcc -Wall -pedantic -ansi -lm -o manu_sim.out model_system.o calculate_functions.o main.o

main.o: model_system.h calculate_functions.h constants.h
	gcc -Wall -pedantic -ansi -c main.c

calculate_functions.o: calculate_functions.h
	gcc -Wall -pedantic -ansi -c calculate_functions.c

model_system.o: model_system.h
	gcc -Wall -pedantic -ansi -c model_system.c

clean:
	rm manu_sim model_system.o calculate_functions.o